// List of major Indian and international airports for autocomplete and booking
const airports = [
  // Major Indian Airports
  { code: "DEL", name: "Delhi", full: "DEL - Delhi" },
  { code: "BOM", name: "Mumbai", full: "BOM - Mumbai" },
  { code: "BLR", name: "Bengaluru", full: "BLR - Bengaluru" },
  { code: "MAA", name: "Chennai", full: "MAA - Chennai" },
  { code: "HYD", name: "Hyderabad", full: "HYD - Hyderabad" },
  { code: "CCU", name: "Kolkata", full: "CCU - Kolkata" },
  { code: "COK", name: "Kochi", full: "COK - Kochi" },
  { code: "AMD", name: "Ahmedabad", full: "AMD - Ahmedabad" },
  { code: "GOI", name: "Goa Dabolim", full: "GOI - Goa Dabolim" },
  { code: "PNQ", name: "Pune", full: "PNQ - Pune" },
  { code: "JAI", name: "Jaipur", full: "JAI - Jaipur" },
  { code: "ATQ", name: "Amritsar", full: "ATQ - Amritsar" },
  { code: "TRV", name: "Thiruvananthapuram", full: "TRV - Thiruvananthapuram" },
  { code: "GAU", name: "Guwahati", full: "GAU - Guwahati" },
  { code: "IXC", name: "Chandigarh", full: "IXC - Chandigarh" },
  { code: "LKO", name: "Lucknow", full: "LKO - Lucknow" },
  { code: "CJB", name: "Coimbatore", full: "CJB - Coimbatore" },
  { code: "IXE", name: "Mangaluru", full: "IXE - Mangaluru" },
  { code: "IXB", name: "Bagdogra", full: "IXB - Bagdogra" },
  { code: "IXM", name: "Madurai", full: "IXM - Madurai" },
  { code: "NAG", name: "Nagpur", full: "NAG - Nagpur" },
  { code: "BBI", name: "Bhubaneswar", full: "BBI - Bhubaneswar" },
  { code: "IDR", name: "Indore", full: "IDR - Indore" },
  { code: "VTZ", name: "Visakhapatnam", full: "VTZ - Visakhapatnam" },
  { code: "VNS", name: "Varanasi", full: "VNS - Varanasi" },
  { code: "STV", name: "Surat", full: "STV - Surat" },
  { code: "TRZ", name: "Tiruchirappalli", full: "TRZ - Tiruchirappalli" },
  { code: "SXR", name: "Srinagar", full: "SXR - Srinagar" },
  { code: "IMF", name: "Imphal", full: "IMF - Imphal" },
  { code: "CNN", name: "Kannur", full: "CNN - Kannur" },
  { code: "PAT", name: "Patna", full: "PAT - Patna" },
  { code: "GAY", name: "Gaya", full: "GAY - Gaya" },
  { code: "IXR", name: "Ranchi", full: "IXR - Ranchi" },
  { code: "BDQ", name: "Vadodara", full: "BDQ - Vadodara" },
  { code: "BHO", name: "Bhopal", full: "BHO - Bhopal" },
  { code: "IXJ", name: "Jammu", full: "IXJ - Jammu" },
  { code: "IXS", name: "Silchar", full: "IXS - Silchar" },
  { code: "HBX", name: "Hubballi", full: "HBX - Hubballi" },
  { code: "DIB", name: "Dibrugarh", full: "DIB - Dibrugarh" },
  { code: "IXU", name: "Aurangabad", full: "IXU - Aurangabad" },
  { code: "TIR", name: "Tirupati", full: "TIR - Tirupati" },
  { code: "RPR", name: "Raipur", full: "RPR - Raipur" },
  { code: "RAJ", name: "Rajkot", full: "RAJ - Rajkot" },
  { code: "RJA", name: "Rajahmundry", full: "RJA - Rajahmundry" },
  { code: "IXL", name: "Leh", full: "IXL - Leh" },
  { code: "IXD", name: "Prayagraj", full: "IXD - Prayagraj" },
  { code: "JLR", name: "Jabalpur", full: "JLR - Jabalpur" },
  { code: "IXA", name: "Agartala", full: "IXA - Agartala" },
  { code: "GOP", name: "Gorakhpur", full: "GOP - Gorakhpur" },
  { code: "AGX", name: "Agatti", full: "AGX - Agatti" },
  { code: "CDP", name: "Kadapa", full: "CDP - Kadapa" },
  { code: "KJB", name: "Kurnool", full: "KJB - Kurnool" },
  { code: "PUT", name: "Puttaparthi", full: "PUT - Puttaparthi" },
  { code: "HGI", name: "Itanagar", full: "HGI - Itanagar" },
  { code: "IXT", name: "Pasighat", full: "IXT - Pasighat" },
  { code: "TEI", name: "Tezu", full: "TEI - Tezu" },
  { code: "ZER", name: "Ziro", full: "ZER - Ziro" },
  { code: "RUP", name: "Rupsi", full: "RUP - Rupsi" },
  { code: "JRH", name: "Jorhat", full: "JRH - Jorhat" },
  { code: "IXI", name: "North Lakhimpur", full: "IXI - North Lakhimpur" },
  { code: "TEZ", name: "Tezpur", full: "TEZ - Tezpur" },
  { code: "DBR", name: "Darbhanga", full: "DBR - Darbhanga" },
  { code: "PAB", name: "Bilaspur", full: "PAB - Bilaspur" },
  { code: "JGB", name: "Jagdalpur", full: "JGB - Jagdalpur" },
  { code: "AHA", name: "Ambikapur", full: "AHA - Ambikapur" },
  { code: "GOX", name: "Goa Manohar (Mopa)", full: "GOX - Goa Manohar (Mopa)" },
  { code: "BHJ", name: "Bhuj", full: "BHJ - Bhuj" },
  { code: "IXY", name: "Kandla", full: "IXY - Kandla" },
  { code: "JGA", name: "Jamnagar", full: "JGA - Jamnagar" },
  { code: "PBD", name: "Porbandar", full: "PBD - Porbandar" },
  { code: "BHU", name: "Bhavnagar", full: "BHU - Bhavnagar" },
  { code: "HSS", name: "Hisar", full: "HSS - Hisar" },
  { code: "DHM", name: "Kangra (Gaggal)", full: "DHM - Kangra (Gaggal)" },
  {
    code: "KUU",
    name: "Kullu Manali (Bhuntar)",
    full: "KUU - Kullu Manali (Bhuntar)",
  },
  { code: "SLV", name: "Shimla", full: "SLV - Shimla" },
  { code: "IXW", name: "Jamshedpur", full: "IXW - Jamshedpur" },
  { code: "BEP", name: "Bellary", full: "BEP - Bellary" },
  { code: "IXG", name: "Belagavi", full: "IXG - Belagavi" },
  { code: "MYQ", name: "Mysore", full: "MYQ - Mysore" },
  { code: "GBI", name: "Kalaburagi", full: "GBI - Kalaburagi" },
  { code: "HJR", name: "Khajuraho", full: "HJR - Khajuraho" },
  { code: "TNI", name: "Satna", full: "TNI - Satna" },
  { code: "GWL", name: "Gwalior", full: "GWL - Gwalior" },
  { code: "SAG", name: "Shirdi", full: "SAG - Shirdi" },
  { code: "ISK", name: "Nashik", full: "ISK - Nashik" },
  { code: "YTL", name: "Yavatmal", full: "YTL - Yavatmal" },
  { code: "NDC", name: "Nanded", full: "NDC - Nanded" },
  { code: "KLH", name: "Kolhapur", full: "KLH - Kolhapur" },
  { code: "SHL", name: "Shillong", full: "SHL - Shillong" },
  { code: "AJL", name: "Aizawl", full: "AJL - Aizawl" },
  { code: "DMU", name: "Dimapur", full: "DMU - Dimapur" },
  { code: "JSA", name: "Jharsuguda", full: "JSA - Jharsuguda" },
  { code: "PYB", name: "Jeypore", full: "PYB - Jeypore" },
  { code: "PNY", name: "Puducherry", full: "PNY - Puducherry" },
  { code: "BUP", name: "Bathinda", full: "BUP - Bathinda" },
  { code: "IXP", name: "Pathankot", full: "IXP - Pathankot" },
  { code: "LUH", name: "Ludhiana", full: "LUH - Ludhiana" },
  { code: "AIP", name: "Adampur", full: "AIP - Adampur" },
  { code: "BKB", name: "Bikaner", full: "BKB - Bikaner" },
  { code: "KTU", name: "Kota", full: "KTU - Kota" },
  { code: "KQH", name: "Kishangarh", full: "KQH - Kishangarh" },
  { code: "JDH", name: "Jodhpur", full: "JDH - Jodhpur" },
  { code: "UDR", name: "Udaipur", full: "UDR - Udaipur" },
  { code: "JSA", name: "Jaisalmer", full: "JSA - Jaisalmer" },
  { code: "PYG", name: "Pakyong", full: "PYG - Pakyong" },
  { code: "TCR", name: "Thoothukudi", full: "TCR - Thoothukudi" },
  { code: "SXV", name: "Salem", full: "SXV - Salem" },
  { code: "KNU", name: "Kanpur", full: "KNU - Kanpur" },
  { code: "VGA", name: "Vijayawada", full: "VGA - Vijayawada" },
  { code: "IXZ", name: "Port Blair", full: "IXZ - Port Blair" },
  { code: "BEK", name: "Bareilly", full: "BEK - Bareilly" },
  { code: "AYJ", name: "Ayodhya", full: "AYJ - Ayodhya" },
  { code: "DGH", name: "Deoghar", full: "DGH - Deoghar" },
  { code: "DIU", name: "Diu", full: "DIU - Diu" },
  { code: "CCJ", name: "Kozhikode", full: "CCJ - Kozhikode" },
  { code: "DEP", name: "Daporijo", full: "DEP - Daporijo" },
  { code: "IXQ", name: "Kamalpur", full: "IXQ - Kamalpur" },
  { code: "IXK", name: "Keshod", full: "IXK - Keshod" },
  { code: "JLW", name: "Jalgaon", full: "JLW - Jalgaon" },
  { code: "AKD", name: "Akola", full: "AKD - Akola" },
  { code: "COH", name: "Cooch Behar", full: "COH - Cooch Behar" },
  { code: "RGH", name: "Balurghat", full: "RGH - Balurghat" },
  { code: "DBD", name: "Dhanbad", full: "DBD - Dhanbad" },
  { code: "GUX", name: "Guna", full: "GUX - Guna" },
  { code: "IXH", name: "Kailashahar", full: "IXH - Kailashahar" },
  { code: "IXN", name: "Khowai", full: "IXN - Khowai" },
  { code: "SSL", name: "Solapur", full: "SSL - Solapur" },
  { code: "BKR", name: "Bokaro", full: "BKR - Bokaro" },
  { code: "NNS", name: "Pithoragarh", full: "NNS - Pithoragarh" },
  { code: "PZY", name: "Pali", full: "PZY - Pali" },
  { code: "VEPU", name: "Purnia", full: "VEPU - Purnia" }, // Placeholder as IATA not widely published
  { code: "MZU", name: "Muzaffarpur", full: "MZU - Muzaffarpur" },
  { code: "VERL", name: "Raxaul", full: "VERL - Raxaul" }, // Placeholder
  { code: "IN0026", name: "Korba", full: "IN0026 - Korba" }, // Placeholder
  { code: "DLI", name: "Daman", full: "DLI - Daman" },

  // Major International Airports
  { code: "JFK", name: "New York", full: "JFK - New York" },
  { code: "LAX", name: "Los Angeles", full: "LAX - Los Angeles" },
  { code: "ORD", name: "Chicago O'Hare", full: "ORD - Chicago O'Hare" },
  { code: "DFW", name: "Dallas Fort Worth", full: "DFW - Dallas Fort Worth" },
  { code: "ATL", name: "Atlanta", full: "ATL - Atlanta" },
  { code: "DEN", name: "Denver", full: "DEN - Denver" },
  { code: "SFO", name: "San Francisco", full: "SFO - San Francisco" },
  { code: "LAS", name: "Las Vegas", full: "LAS - Las Vegas" },
  { code: "MIA", name: "Miami", full: "MIA - Miami" },
  { code: "BOS", name: "Boston", full: "BOS - Boston" },
  { code: "SEA", name: "Seattle", full: "SEA - Seattle" },
  { code: "IAH", name: "Houston", full: "IAH - Houston" },
  { code: "MCO", name: "Orlando", full: "MCO - Orlando" },
  { code: "PHX", name: "Phoenix", full: "PHX - Phoenix" },
  { code: "DTW", name: "Detroit", full: "DTW - Detroit" },
  { code: "LHR", name: "London Heathrow", full: "LHR - London Heathrow" },
  {
    code: "CDG",
    name: "Paris Charles de Gaulle",
    full: "CDG - Paris Charles de Gaulle",
  },
  { code: "FRA", name: "Frankfurt", full: "FRA - Frankfurt" },
  { code: "AMS", name: "Amsterdam Schiphol", full: "AMS - Amsterdam Schiphol" },
  { code: "MAD", name: "Madrid", full: "MAD - Madrid" },
  { code: "BCN", name: "Barcelona", full: "BCN - Barcelona" },
  { code: "NRT", name: "Tokyo Narita", full: "NRT - Tokyo Narita" },
  { code: "HND", name: "Tokyo Haneda", full: "HND - Tokyo Haneda" },
  { code: "ICN", name: "Seoul Incheon", full: "ICN - Seoul Incheon" },
  { code: "SIN", name: "Singapore Changi", full: "SIN - Singapore Changi" },
  {
    code: "BKK",
    name: "Bangkok Suvarnabhumi",
    full: "BKK - Bangkok Suvarnabhumi",
  },
  { code: "HKG", name: "Hong Kong", full: "HKG - Hong Kong" },
  { code: "SYD", name: "Sydney", full: "SYD - Sydney" },
  { code: "MEL", name: "Melbourne", full: "MEL - Melbourne" },
  { code: "YVR", name: "Vancouver", full: "YVR - Vancouver" },
  { code: "YYZ", name: "Toronto Pearson", full: "YYZ - Toronto Pearson" },
  { code: "YUL", name: "Montreal Trudeau", full: "YUL - Montreal Trudeau" },
  { code: "DXB", name: "Dubai", full: "DXB - Dubai" },
  { code: "IST", name: "Istanbul", full: "IST - Istanbul" },
  { code: "FCO", name: "Rome Fiumicino", full: "FCO - Rome Fiumicino" },
  { code: "MXP", name: "Milan Malpensa", full: "MXP - Milan Malpensa" },
  { code: "ZRH", name: "Zurich", full: "ZRH - Zurich" },
  { code: "VIE", name: "Vienna", full: "VIE - Vienna" },
  { code: "CPH", name: "Copenhagen", full: "CPH - Copenhagen" },
  {
    code: "ARN",
    name: "Stockholm Arlanda",
    full: "ARN - Stockholm Arlanda",
  },
  { code: "OSL", name: "Oslo Gardermoen", full: "OSL - Oslo Gardermoen" },
  { code: "HEL", name: "Helsinki", full: "HEL - Helsinki" },
  { code: "WAW", name: "Warsaw Chopin", full: "WAW - Warsaw Chopin" },
  { code: "PRG", name: "Prague", full: "PRG - Prague" },
  { code: "BUD", name: "Budapest", full: "BUD - Budapest" },
  { code: "ATH", name: "Athens", full: "ATH - Athens" },
  { code: "LIS", name: "Lisbon", full: "LIS - Lisbon" },
  { code: "OPO", name: "Porto", full: "OPO - Porto" },
  { code: "DUB", name: "Dublin", full: "DUB - Dublin" },
  { code: "EDI", name: "Edinburgh", full: "EDI - Edinburgh" },
  { code: "MAN", name: "Manchester", full: "MAN - Manchester" },
  { code: "BHX", name: "Birmingham", full: "BHX - Birmingham" },
  { code: "GLA", name: "Glasgow", full: "GLA - Glasgow" },
  { code: "NCL", name: "Newcastle", full: "NCL - Newcastle" },
  { code: "LPL", name: "Liverpool", full: "LPL - Liverpool" },
  { code: "BRS", name: "Bristol", full: "BRS - Bristol" },
  { code: "LTN", name: "London Luton", full: "LTN - London Luton" },
  { code: "STN", name: "London Stansted", full: "STN - London Stansted" },
  { code: "LCY", name: "London City", full: "LCY - London City" },
  { code: "LGW", name: "London Gatwick", full: "LGW - London Gatwick" },

  // More International Airports (Selected for variety and commonality)
  { code: "ADD", name: "Addis Ababa", full: "ADD - Addis Ababa" },
  { code: "ADL", name: "Adelaide", full: "ADL - Adelaide" },
  { code: "AKL", name: "Auckland", full: "AKL - Auckland" },
  { code: "ALG", name: "Algiers", full: "ALG - Algiers" },
  { code: "AMM", name: "Amman", full: "AMM - Amman" },
  { code: "ANC", name: "Anchorage", full: "ANC - Anchorage" },
  { code: "ANU", name: "Antigua", full: "ANU - Antigua" },
  { code: "AUH", name: "Abu Dhabi", full: "AUH - Abu Dhabi" },
  { code: "BNA", name: "Nashville", full: "BNA - Nashville" },
  { code: "BNE", name: "Brisbane", full: "BNE - Brisbane" },
  { code: "CPT", name: "Cape Town", full: "CPT - Cape Town" },
  { code: "CAI", name: "Cairo", full: "CAI - Cairo" },
  { code: "CLT", name: "Charlotte", full: "CLT - Charlotte" },
  { code: "DOH", name: "Doha Hamad", full: "DOH - Doha Hamad" },
  {
    code: "DCA",
    name: "Washington Reagan",
    full: "DCA - Washington Reagan",
  },
  {
    code: "EZE",
    name: "Buenos Aires Ezeiza",
    full: "EZE - Buenos Aires Ezeiza",
  },
  {
    code: "GIG",
    name: "Rio de Janeiro Galeao",
    full: "GIG - Rio de Janeiro Galeao",
  },
  {
    code: "GRU",
    name: "Sao Paulo Guarulhos",
    full: "GRU - Sao Paulo Guarulhos",
  },
  { code: "JNB", name: "Johannesburg", full: "JNB - Johannesburg" },
  { code: "KUL", name: "Kuala Lumpur", full: "KUL - Kuala Lumpur" },
  { code: "MEX", name: "Mexico City", full: "MEX - Mexico City" },
  {
    code: "MSP",
    name: "Minneapolis St. Paul",
    full: "MSP - Minneapolis St. Paul",
  },
  { code: "MUC", name: "Munich", full: "MUC - Munich" },
  {
    code: "NBO",
    name: "Nairobi Jomo Kenyatta",
    full: "NBO - Nairobi Jomo Kenyatta",
  },
  { code: "OSAKA", name: "Osaka Kansai", full: "KIX - Osaka Kansai" },
  { code: "PHL", name: "Philadelphia", full: "PHL - Philadelphia" },
  { code: "PUJ", name: "Punta Cana", full: "PUJ - Punta Cana" },
  {
    code: "RUH",
    name: "Riyadh King Khalid",
    full: "RUH - Riyadh King Khalid",
  },
  { code: "SCL", name: "Santiago", full: "SCL - Santiago" },
  { code: "SEA", name: "Seattle-Tacoma", full: "SEA - Seattle-Tacoma" },
  { code: "TPE", name: "Taipei Taoyuan", full: "TPE - Taipei Taoyuan" },
  {
    code: "TLV",
    name: "Tel Aviv Ben Gurion",
    full: "TLV - Tel Aviv Ben Gurion",
  },
  {
    code: "VCE",
    name: "Venice Marco Polo",
    full: "VCE - Venice Marco Polo",
  },
  { code: "YYC", name: "Calgary", full: "YYC - Calgary" },
  { code: "YWG", name: "Winnipeg", full: "YWG - Winnipeg" },
  { code: "YEG", name: "Edmonton", full: "YEG - Edmonton" },
  { code: "YOW", name: "Ottawa", full: "YOW - Ottawa" },
  { code: "HOU", name: "Houston Hobby", full: "HOU - Houston Hobby" },
  { code: "SJC", name: "San Jose (CA)", full: "SJC - San Jose (CA)" },
  { code: "PDX", name: "Portland (OR)", full: "PDX - Portland (OR)" },
  { code: "CLE", name: "Cleveland", full: "CLE - Cleveland" },
  { code: "IND", name: "Indianapolis", full: "IND - Indianapolis" },
  { code: "STL", name: "St. Louis", full: "STL - St. Louis" },
  { code: "MKE", name: "Milwaukee", full: "MKE - Milwaukee" },
  { code: "RDU", name: "Raleigh-Durham", full: "RDU - Raleigh-Durham" },
  { code: "ORF", name: "Norfolk", full: "ORF - Norfolk" },
  { code: "SAV", name: "Savannah", full: "SAV - Savannah" },
  { code: "CHS", name: "Charleston", full: "CHS - Charleston" },
  { code: "PBI", name: "Palm Beach", full: "PBI - Palm Beach" },
  { code: "RSW", name: "Fort Myers", full: "RSW - Fort Myers" },
  { code: "TPA", name: "Tampa", full: "TPA - Tampa" },
  { code: "JAX", name: "Jacksonville", full: "JAX - Jacksonville" },
  { code: "MEM", name: "Memphis", full: "MEM - Memphis" },
  { code: "BHM", name: "Birmingham (AL)", full: "BHM - Birmingham (AL)" },
  { code: "MSY", name: "New Orleans", full: "MSY - New Orleans" },
  { code: "SAT", name: "San Antonio", full: "SAT - San Antonio" },
  { code: "AUS", name: "Austin", full: "AUS - Austin" },
  { code: "OKC", name: "Oklahoma City", full: "OKC - Oklahoma City" },
  { code: "TUL", name: "Tulsa", full: "TUL - Tulsa" },
  { code: "ABQ", name: "Albuquerque", full: "ABQ - Albuquerque" },
  { code: "SLC", name: "Salt Lake City", full: "SLC - Salt Lake City" },
  { code: "PDX", name: "Portland (OR)", full: "PDX - Portland (OR)" },
  { code: "SMF", name: "Sacramento", full: "SMF - Sacramento" },
  { code: "SAN", name: "San Diego", full: "SAN - San Diego" },
  { code: "ANC", name: "Anchorage", full: "ANC - Anchorage" },
  { code: "FAI", name: "Fairbanks", full: "FAI - Fairbanks" },
  { code: "HNL", name: "Honolulu", full: "HNL - Honolulu" },
  { code: "OGG", name: "Kahului (Maui)", full: "OGG - Kahului (Maui)" },
  { code: "KOA", name: "Kona (Hawaii)", full: "KOA - Kona (Hawaii)" },
  { code: "LIH", name: "Lihue (Kauai)", full: "LIH - Lihue (Kauai)" },
  {
    code: "CDG",
    name: "Paris Charles de Gaulle",
    full: "CDG - Paris Charles de Gaulle",
  },
  { code: "ORY", name: "Paris Orly", full: "ORY - Paris Orly" },
  { code: "NCE", name: "Nice", full: "NCE - Nice" },
  { code: "MRS", name: "Marseille", full: "MRS - Marseille" },
  { code: "LYS", name: "Lyon", full: "LYS - Lyon" },
  { code: "TXL", name: "Berlin Tegel", full: "TXL - Berlin Tegel" }, // Note: TXL is now closed, BER is main airport
  {
    code: "BER",
    name: "Berlin Brandenburg",
    full: "BER - Berlin Brandenburg",
  },
  { code: "DUS", name: "Dusseldorf", full: "DUS - Dusseldorf" },
  { code: "HAM", name: "Hamburg", full: "HAM - Hamburg" },
  { code: "STR", name: "Stuttgart", full: "STR - Stuttgart" },
  {
    code: "DME",
    name: "Moscow Domodedovo",
    full: "DME - Moscow Domodedovo",
  },
  {
    code: "SVO",
    name: "Moscow Sheremetyevo",
    full: "SVO - Moscow Sheremetyevo",
  },
  { code: "LED", name: "St. Petersburg", full: "LED - St. Petersburg" },
  { code: "VKO", name: "Moscow Vnukovo", full: "VKO - Moscow Vnukovo" },
  { code: "GVA", name: "Geneva", full: "GVA - Geneva" },
  { code: "BRU", name: "Brussels", full: "BRU - Brussels" },
  { code: "DUS", name: "Dusseldorf", full: "DUS - Dusseldorf" },
  {
    code: "PMI",
    name: "Palma de Mallorca",
    full: "PMI - Palma de Mallorca",
  },
  { code: "AGP", name: "Malaga", full: "AGP - Malaga" },
  { code: "IBZ", name: "Ibiza", full: "IBZ - Ibiza" },
  { code: "TFS", name: "Tenerife South", full: "TFS - Tenerife South" },
  { code: "LPA", name: "Gran Canaria", full: "LPA - Gran Canaria" },
  { code: "PUY", name: "Pula", full: "PUY - Pula" },
  { code: "DBV", name: "Dubrovnik", full: "DBV - Dubrovnik" },
  { code: "SPU", name: "Split", full: "SPU - Split" },
  { code: "ZAG", name: "Zagreb", full: "ZAG - Zagreb" },
  {
    code: "OTP",
    name: "Bucharest Otopeni",
    full: "OTP - Bucharest Otopeni",
  },
  { code: "SOF", name: "Sofia", full: "SOF - Sofia" },
  { code: "BEG", name: "Belgrade", full: "BEG - Belgrade" },
  { code: "KBP", name: "Kyiv Boryspil", full: "KBP - Kyiv Boryspil" },
  { code: "GYD", name: "Baku", full: "GYD - Baku" },
  { code: "TBS", name: "Tbilisi", full: "TBS - Tbilisi" },
  { code: "EVN", name: "Yerevan", full: "EVN - Yerevan" },
  { code: "ALA", name: "Almaty", full: "ALA - Almaty" },
  { code: "TAS", name: "Tashkent", full: "TAS - Tashkent" },
  { code: "BJS", name: "Beijing Capital", full: "PEK - Beijing Capital" }, // BJS is city code, PEK is airport
  { code: "PKX", name: "Beijing Daxing", full: "PKX - Beijing Daxing" },
  { code: "PVG", name: "Shanghai Pudong", full: "PVG - Shanghai Pudong" },
  {
    code: "SHA",
    name: "Shanghai Hongqiao",
    full: "SHA - Shanghai Hongqiao",
  },
  { code: "CAN", name: "Guangzhou", full: "CAN - Guangzhou" },
  {
    code: "CTU",
    name: "Chengdu Shuangliu",
    full: "CTU - Chengdu Shuangliu",
  },
  { code: "CKG", name: "Chongqing", full: "CKG - Chongqing" },
  { code: "XMN", name: "Xiamen", full: "XMN - Xiamen" },
  { code: "SHE", name: "Shenyang", full: "SHE - Shenyang" },
  { code: "KMG", name: "Kunming", full: "KMG - Kunming" },
  { code: "TNA", name: "Jinan", full: "TNA - Jinan" },
  { code: "URC", name: "Urumqi", full: "URC - Urumqi" },
  { code: "XIY", name: "Xi'an", full: "XIY - Xi'an" },
  { code: "KIX", name: "Osaka Kansai", full: "KIX - Osaka Kansai" },
  { code: "ITM", name: "Osaka Itami", full: "ITM - Osaka Itami" },
  { code: "FUK", name: "Fukuoka", full: "FUK - Fukuoka" },
  {
    code: "CTS",
    name: "Sapporo New Chitose",
    full: "CTS - Sapporo New Chitose",
  },
  { code: "OKA", name: "Okinawa Naha", full: "OKA - Okinawa Naha" },
  { code: "PUS", name: "Busan Gimhae", full: "PUS - Busan Gimhae" },
  { code: "CJU", name: "Jeju", full: "CJU - Jeju" },
  {
    code: "MNL",
    name: "Manila Ninoy Aquino",
    full: "MNL - Manila Ninoy Aquino",
  },
  { code: "CEB", name: "Cebu Mactan-Cebu", full: "CEB - Cebu Mactan-Cebu" },
  { code: "SGN", name: "Ho Chi Minh City", full: "SGN - Ho Chi Minh City" },
  { code: "HAN", name: "Hanoi Noi Bai", full: "HAN - Hanoi Noi Bai" },
  { code: "DAD", name: "Da Nang", full: "DAD - Da Nang" },
  { code: "KTM", name: "Kathmandu", full: "KTM - Kathmandu" },
  {
    code: "CMB",
    name: "Colombo Bandaranaike",
    full: "CMB - Colombo Bandaranaike",
  },
  { code: "DAC", name: "Dhaka", full: "DAC - Dhaka" },
  { code: "MLE", name: "Malé", full: "MLE - Malé" },
  { code: "VTE", name: "Vientiane", full: "VTE - Vientiane" },
  { code: "PNH", name: "Phnom Penh", full: "PNH - Phnom Penh" },
  { code: "REP", name: "Siem Reap", full: "REP - Siem Reap" },
  { code: "RGN", name: "Yangon", full: "RGN - Yangon" },
  { code: "MDL", name: "Mandalay", full: "MDL - Mandalay" },
  { code: "LOP", name: "Lombok", full: "LOP - Lombok" },
  { code: "DPS", name: "Denpasar (Bali)", full: "DPS - Denpasar (Bali)" },
  {
    code: "CGK",
    name: "Jakarta Soekarno-Hatta",
    full: "CGK - Jakarta Soekarno-Hatta",
  },
  { code: "SUB", name: "Surabaya", full: "SUB - Surabaya" },
  {
    code: "JED",
    name: "Jeddah King Abdulaziz",
    full: "JED - Jeddah King Abdulaziz",
  },
  { code: "KWI", name: "Kuwait City", full: "KWI - Kuwait City" },
  { code: "BAH", name: "Bahrain", full: "BAH - Bahrain" },
  { code: "BEY", name: "Beirut", full: "BEY - Beirut" },
  { code: "DMM", name: "Dammam King Fahd", full: "DMM - Dammam King Fahd" },
  { code: "AUH", name: "Abu Dhabi", full: "AUH - Abu Dhabi" },
  {
    code: "GYD",
    name: "Baku Heydar Aliyev",
    full: "GYD - Baku Heydar Aliyev",
  },
  { code: "ASB", name: "Ashgabat", full: "ASB - Ashgabat" },
  { code: "MCT", name: "Muscat", full: "MCT - Muscat" },
  { code: "BNE", name: "Brisbane", full: "BNE - Brisbane" },
  { code: "PER", name: "Perth", full: "PER - Perth" },
  { code: "ADL", name: "Adelaide", full: "ADL - Adelaide" },
  { code: "AKL", name: "Auckland", full: "AKL - Auckland" },
  { code: "CHC", name: "Christchurch", full: "CHC - Christchurch" },
  { code: "WLG", name: "Wellington", full: "WLG - Wellington" },
  { code: "FIJ", name: "Nadi", full: "FIJ - Nadi" },
  { code: "PPT", name: "Papeete Faa'a", full: "PPT - Papeete Faa'a" },
  {
    code: "NOU",
    name: "Nouméa La Tontouta",
    full: "NOU - Nouméa La Tontouta",
  },
  { code: "SAB", name: "Saba", full: "SAB - Saba" },
  { code: "SXM", name: "Saint Maarten", full: "SXM - Saint Maarten" },
  { code: "BGI", name: "Bridgetown", full: "BGI - Bridgetown" },
  { code: "HAV", name: "Havana", full: "HAV - Havana" },
  { code: "KIN", name: "Kingston", full: "KIN - Kingston" },
  { code: "MBJ", name: "Montego Bay", full: "MBJ - Montego Bay" },
  { code: "NAS", name: "Nassau", full: "NAS - Nassau" },
  { code: "UVF", name: "Saint Lucia", full: "UVF - Saint Lucia" },
  { code: "PLS", name: "Providenciales", full: "PLS - Providenciales" },
  { code: "PVR", name: "Puerto Vallarta", full: "PVR - Puerto Vallarta" },
  { code: "CUN", name: "Cancun", full: "CUN - Cancun" },
  { code: "MEX", name: "Mexico City", full: "MEX - Mexico City" },
  { code: "GDL", name: "Guadalajara", full: "GDL - Guadalajara" },
  {
    code: "PTY",
    name: "Panama City Tocumen",
    full: "PTY - Panama City Tocumen",
  },
  {
    code: "SJO",
    name: "San Jose (Costa Rica)",
    full: "SJO - San Jose (Costa Rica)",
  },
  { code: "SAL", name: "San Salvador", full: "SAL - San Salvador" },
  { code: "BOG", name: "Bogotá El Dorado", full: "BOG - Bogotá El Dorado" },
  {
    code: "LIM",
    name: "Lima Jorge Chávez",
    full: "LIM - Lima Jorge Chávez",
  },
  {
    code: "UIO",
    name: "Quito Mariscal Sucre",
    full: "UIO - Quito Mariscal Sucre",
  },
  { code: "SCL", name: "Santiago", full: "SCL - Santiago" },
  {
    code: "GRU",
    name: "Sao Paulo Guarulhos",
    full: "GRU - Sao Paulo Guarulhos",
  },
  {
    code: "GIG",
    name: "Rio de Janeiro Galeao",
    full: "GIG - Rio de Janeiro Galeao",
  },
  { code: "MDZ", name: "Mendoza", full: "MDZ - Mendoza" },
  { code: "COR", name: "Cordoba", full: "COR - Cordoba" },
];
